### ISSUE TITLE
any change to find a documentation about it?

### ISSUE THREAD

**Issue by vpereira** [mpiannucci/surfpy#5]
The project looks pretty interesting. However there is 0 documentation about. What would be the best way to get introduced and contribute to this project?

**Comment by mpiannucci** [comment]
Yeah this is basically my code that I run all my surfing apps in the cloud with. I haven’t had time to document as much as I would like to because it’s been mostly for only personal use, although I definitely would love others to benefit from it.

I can help you find what you are looking for if you know what your goals are and what pieces you have questions about!

**Comment by vpereira** [comment]
hey @mpiannucci I have as well some surfing apps running in the cloud. I will try to understand all the features that you have. I will start looking into the wavemodel and NOAAModel, thanks!

**Comment by mpiannucci** [comment]
Ah okay, most of that looks like it is installed by default by anaconda and it is not required by this library. Assuming `surfpy` is cloned in the same directory as `grippy` the following `requirements.txt` should be sufficient: 
```
requests
numpy
matplotlib
```
I will update the readme with this information. 

Thank you!
